name: tp1
networks:
  middleware_testing_net:
    external: 'true'
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  airportHandler1:
    container_name: airportHandler1
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: airport_handler:latest
    networks:
    - middleware_testing_net
    restart: on-failure
    volumes:
    - ./airportHandler/config.ini:/config.ini
  airportHandler2:
    container_name: airportHandler2
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: airport_handler:latest
    networks:
    - middleware_testing_net
    restart: on-failure
    volumes:
    - ./airportHandler/config.ini:/config.ini
  client:
    container_name: client
    depends_on:
    - clientHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: client:latest
    networks:
    - middleware_testing_net
    restart: on-failure
    volumes:
    - ./client/config.ini:/config.ini
    - ./client/airports-codepublic.csv:/airports-codepublic.csv
  clientHandler:
    container_name: clientHandler
    depends_on:
    - airportHandler1
    - airportHandler2
    - query1Handler1
    - query1Handler2
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: client_handler:latest
    networks:
    - middleware_testing_net
    restart: on-failure
    volumes:
    - ./clientHandler/config.ini:/config.ini
  query1Handler1:
    container_name: query1Handler1
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: query1_handler:latest
    networks:
    - middleware_testing_net
    restart: on-failure
    volumes:
    - ./query1Handler/config.ini:/config.ini
  query1Handler2:
    container_name: query1Handler2
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: query1_handler:latest
    networks:
    - middleware_testing_net
    restart: on-failure
    volumes:
    - ./query1Handler/config.ini:/config.ini
  resultHandler:
    container_name: resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: result_handler:latest
    networks:
    - middleware_testing_net
    restart: on-failure
    volumes:
    - ./resultHandler/config.ini:/config.ini
version: '3.9'
