name: tp1
networks:
  middleware_testing_net:
    external: 'true'
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  airportHandler1:
    container_name: query2Handler1
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=3
    image: query2_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query2/query2Handler/config.ini:/config.ini
  airportHandler2:
    container_name: query2Handler2
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=3
    image: query2_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query2/query2Handler/config.ini:/config.ini
  airportHandler3:
    container_name: query2Handler3
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=3
    image: query2_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query2/query2Handler/config.ini:/config.ini
  client:
    container_name: client
    depends_on:
    - clientHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    image: client:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./client/config.ini:/config.ini
    - ./client/airports-codepublic.csv:/airports-codepublic.csv
    - ./client/itineraries_random_2M.csv:/itineraries_random_2M.csv
    - ./client/results.csv:/results.csv
  clientHandler:
    container_name: clientHandler
    depends_on:
    - airportHandler1
    - airportHandler2
    - airportHandler3
    - query1Handler1
    - query4Handler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: client_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./clientHandler/config.ini:/config.ini
  query1Handler1:
    container_name: query1Handler1
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=1
    image: query1_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query1/query1Handler/config.ini:/config.ini
  query3Handler:
    container_name: query3Handler
    depends_on:
    - query3Worker1
    - query3Worker2
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    image: query3_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query3/query3Handler/config.ini:/config.ini
  query3Synchronizer:
    container_name: query3Synchronizer
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    image: query3_synchronizer:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query3/query3Synchronizer/config.ini:/config.ini
  query3Worker1:
    container_name: query3Worker1
    depends_on:
    - query3Synchronizer
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=2
    image: query3_worker:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query3/query3Worker/config.ini:/config.ini
  query3Worker2:
    container_name: query3Worker2
    depends_on:
    - query3Synchronizer
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=2
    image: query3_worker:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query3/query3Worker/config.ini:/config.ini
  query4Handler:
    container_name: query4Handler
    depends_on:
    - query4Worker1
    - query4Worker2
    - query4Worker3
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    image: query4_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query4/query4Handler/config.ini:/config.ini
  query4Synchronizer:
    container_name: query4Synchronizer
    depends_on:
    - resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    image: query4_synchronizer:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query4/query4Synchronizer/config.ini:/config.ini
  query4Worker1:
    container_name: query4Worker1
    depends_on:
    - query4Synchronizer
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=3
    image: query4_worker:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query4/query4Worker/config.ini:/config.ini
  query4Worker2:
    container_name: query4Worker2
    depends_on:
    - query4Synchronizer
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=3
    image: query4_worker:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query4/query4Worker/config.ini:/config.ini
  query4Worker3:
    container_name: query4Worker3
    depends_on:
    - query4Synchronizer
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    - PEERS=3
    image: query4_worker:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./query4/query4Worker/config.ini:/config.ini
  resultHandler:
    container_name: resultHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=ERROR
    image: result_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./resultHandler/config.ini:/config.ini
version: '3.9'
