name: tp1
networks:
  middleware_testing_net:
    external: 'true'
    ipam:
      config:
      - subnet: 172.25.125.0/24
      driver: default
services:
  client:
    container_name: client
    depends_on:
    - clientHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: client:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./client/config.ini:/config.ini
    - ./client/airports-codepublic.csv:/airports-codepublic.csv
    - ./client/itineraries_random_2M.csv:/itineraries_random_2M.csv
    - ./client/results.csv:/results.csv
  clientHandler:
    container_name: clientHandler
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    image: client_handler:latest
    networks:
    - middleware_testing_net
    volumes:
    - ./clientHandler/config.ini:/config.ini
version: '3.9'
