version: '3.9'
name: tp1
services:
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./client/config.ini:/config.ini
      - ./client/airports-codepublic.csv:/airports-codepublic.csv
    networks:
      - testing_net

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24